print("input two numbers")
num = input()
num2 = input()
print("addition = ",int(num) + int(num2))
print("substraction = ",int(num) - int(num2))
print("product = ", int(num) * int(num2))
print("qoutiant = ", int(num) / int(num2))
print("reminder = ", int(num) % int(num2))

print("input two numbers")
num = int(input())
num2 = int(input())
print("addition = ",(num) + (num2))
print("substraction = ",(num) - (num2))
print("product = ", (num) * (num2))
print("qoutiant = ", (num) / (num2))
print("reminder = ", (num) % (num2))
